# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: backend_service.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()





import ficus.grpc_pipelines.models.pipelines_pb2 as pipelines__pb2

import ficus.grpc_pipelines.models.util_pb2 as util__pb2

import ficus.grpc_pipelines.models.context_pb2 as context__pb2





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63kend_service.proto\x12\x05\x66icus\x1a\x0fpipelines.proto\x1a\nutil.proto\x1a\rcontext.proto\"f\n\x1aGrpcGetContextValueRequest\x12$\n\x0b\x65xecutionId\x18\x02 \x01(\x0b\x32\x0f.ficus.GrpcGuid\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.ficus.GrpcContextKey\"y\n\x1cGrpcPipelineExecutionRequest\x12%\n\x08pipeline\x18\x01 \x01(\x0b\x32\x13.ficus.GrpcPipeline\x12\x32\n\x0einitialContext\x18\x02 \x03(\x0b\x32\x1a.ficus.GrpcContextKeyValue\"e\n\x1bGrpcPipelineExecutionResult\x12\"\n\x07success\x18\x01 \x01(\x0b\x32\x0f.ficus.GrpcGuidH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x11\n\x0f\x65xecutionResult\"l\n\x19GrpcGetContextValueResult\x12(\n\x05value\x18\x01 \x01(\x0b\x32\x17.ficus.GrpcContextValueH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x14\n\x12\x63ontextValueResult2\xc8\x01\n\x12GrpcBackendService\x12Z\n\x0f\x45xecutePipeline\x12#.ficus.GrpcPipelineExecutionRequest\x1a\".ficus.GrpcPipelineExecutionResult\x12V\n\x0fGetContextValue\x12!.ficus.GrpcGetContextValueRequest\x1a .ficus.GrpcGetContextValueResultb\x06proto3')







_GRPCGETCONTEXTVALUEREQUEST = DESCRIPTOR.message_types_by_name['GrpcGetContextValueRequest']

_GRPCPIPELINEEXECUTIONREQUEST = DESCRIPTOR.message_types_by_name['GrpcPipelineExecutionRequest']

_GRPCPIPELINEEXECUTIONRESULT = DESCRIPTOR.message_types_by_name['GrpcPipelineExecutionResult']

_GRPCGETCONTEXTVALUERESULT = DESCRIPTOR.message_types_by_name['GrpcGetContextValueResult']

GrpcGetContextValueRequest = _reflection.GeneratedProtocolMessageType('GrpcGetContextValueRequest', (_message.Message,), {

  'DESCRIPTOR' : _GRPCGETCONTEXTVALUEREQUEST,

  '__module__' : 'backend_service_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcGetContextValueRequest)

  })

_sym_db.RegisterMessage(GrpcGetContextValueRequest)



GrpcPipelineExecutionRequest = _reflection.GeneratedProtocolMessageType('GrpcPipelineExecutionRequest', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEEXECUTIONREQUEST,

  '__module__' : 'backend_service_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelineExecutionRequest)

  })

_sym_db.RegisterMessage(GrpcPipelineExecutionRequest)



GrpcPipelineExecutionResult = _reflection.GeneratedProtocolMessageType('GrpcPipelineExecutionResult', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEEXECUTIONRESULT,

  '__module__' : 'backend_service_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelineExecutionResult)

  })

_sym_db.RegisterMessage(GrpcPipelineExecutionResult)



GrpcGetContextValueResult = _reflection.GeneratedProtocolMessageType('GrpcGetContextValueResult', (_message.Message,), {

  'DESCRIPTOR' : _GRPCGETCONTEXTVALUERESULT,

  '__module__' : 'backend_service_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcGetContextValueResult)

  })

_sym_db.RegisterMessage(GrpcGetContextValueResult)



_GRPCBACKENDSERVICE = DESCRIPTOR.services_by_name['GrpcBackendService']

if _descriptor._USE_C_DESCRIPTORS == False:



  DESCRIPTOR._options = None

  _GRPCGETCONTEXTVALUEREQUEST._serialized_start=76

  _GRPCGETCONTEXTVALUEREQUEST._serialized_end=178

  _GRPCPIPELINEEXECUTIONREQUEST._serialized_start=180

  _GRPCPIPELINEEXECUTIONREQUEST._serialized_end=301

  _GRPCPIPELINEEXECUTIONRESULT._serialized_start=303

  _GRPCPIPELINEEXECUTIONRESULT._serialized_end=404

  _GRPCGETCONTEXTVALUERESULT._serialized_start=406

  _GRPCGETCONTEXTVALUERESULT._serialized_end=514

  _GRPCBACKENDSERVICE._serialized_start=517

  _GRPCBACKENDSERVICE._serialized_end=717

# @@protoc_insertion_point(module_scope)
