# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: pipelines.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()





import ficus.grpc_pipelines.models.context_pb2 as context__pb2





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpipelines.proto\x12\x05\x66icus\x1a\rcontext.proto\":\n\x0cGrpcPipeline\x12*\n\x05parts\x18\x01 \x03(\x0b\x32\x1b.ficus.GrpcPipelinePartBase\"\x9c\x02\n\x14GrpcPipelinePartBase\x12.\n\x0b\x64\x65\x66\x61ultPart\x18\x01 \x01(\x0b\x32\x17.ficus.GrpcPipelinePartH\x00\x12\x37\n\x0cparallelPart\x18\x02 \x01(\x0b\x32\x1f.ficus.GrpcParallelPipelinePartH\x00\x12O\n\x18simpleContextRequestPart\x18\x03 \x01(\x0b\x32+.ficus.GrpcSimpleContextRequestPipelinePartH\x00\x12\x42\n\x19\x63omplexContextRequestPart\x18\x04 \x01(\x0b\x32\x1d.ficus.GrpcComplexRequestPartH\x00\x42\x06\n\x04part\"]\n\x10GrpcPipelinePart\x12\x0c\n\x04name\x18\x01 \x01(\t\x12;\n\rconfiguration\x18\x02 \x01(\x0b\x32$.ficus.GrpcPipelinePartConfiguration\"\\\n\x1dGrpcPipelinePartConfiguration\x12;\n\x17\x63onfigurationParameters\x18\x01 \x03(\x0b\x32\x1a.ficus.GrpcContextKeyValue\"N\n\x18GrpcParallelPipelinePart\x12\x32\n\rpipelineParts\x18\x01 \x03(\x0b\x32\x1b.ficus.GrpcPipelinePartBase\"N\n\x19GrpcParallelPipelineParts\x12\x31\n\x08pipeline\x18\x01 \x03(\x0b\x32\x1f.ficus.GrpcParallelPipelinePart\"J\n$GrpcSimpleContextRequestPipelinePart\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.ficus.GrpcContextKey\"q\n\x16GrpcComplexRequestPart\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.ficus.GrpcContextKey\x12\x33\n\x12\x62\x65\x66orePipelinePart\x18\x02 \x01(\x0b\x32\x17.ficus.GrpcPipelinePartb\x06proto3')







_GRPCPIPELINE = DESCRIPTOR.message_types_by_name['GrpcPipeline']

_GRPCPIPELINEPARTBASE = DESCRIPTOR.message_types_by_name['GrpcPipelinePartBase']

_GRPCPIPELINEPART = DESCRIPTOR.message_types_by_name['GrpcPipelinePart']

_GRPCPIPELINEPARTCONFIGURATION = DESCRIPTOR.message_types_by_name['GrpcPipelinePartConfiguration']

_GRPCPARALLELPIPELINEPART = DESCRIPTOR.message_types_by_name['GrpcParallelPipelinePart']

_GRPCPARALLELPIPELINEPARTS = DESCRIPTOR.message_types_by_name['GrpcParallelPipelineParts']

_GRPCSIMPLECONTEXTREQUESTPIPELINEPART = DESCRIPTOR.message_types_by_name['GrpcSimpleContextRequestPipelinePart']

_GRPCCOMPLEXREQUESTPART = DESCRIPTOR.message_types_by_name['GrpcComplexRequestPart']

GrpcPipeline = _reflection.GeneratedProtocolMessageType('GrpcPipeline', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINE,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipeline)

  })

_sym_db.RegisterMessage(GrpcPipeline)



GrpcPipelinePartBase = _reflection.GeneratedProtocolMessageType('GrpcPipelinePartBase', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPARTBASE,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePartBase)

  })

_sym_db.RegisterMessage(GrpcPipelinePartBase)



GrpcPipelinePart = _reflection.GeneratedProtocolMessageType('GrpcPipelinePart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePart)

  })

_sym_db.RegisterMessage(GrpcPipelinePart)



GrpcPipelinePartConfiguration = _reflection.GeneratedProtocolMessageType('GrpcPipelinePartConfiguration', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPARTCONFIGURATION,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePartConfiguration)

  })

_sym_db.RegisterMessage(GrpcPipelinePartConfiguration)



GrpcParallelPipelinePart = _reflection.GeneratedProtocolMessageType('GrpcParallelPipelinePart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPARALLELPIPELINEPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcParallelPipelinePart)

  })

_sym_db.RegisterMessage(GrpcParallelPipelinePart)



GrpcParallelPipelineParts = _reflection.GeneratedProtocolMessageType('GrpcParallelPipelineParts', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPARALLELPIPELINEPARTS,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcParallelPipelineParts)

  })

_sym_db.RegisterMessage(GrpcParallelPipelineParts)



GrpcSimpleContextRequestPipelinePart = _reflection.GeneratedProtocolMessageType('GrpcSimpleContextRequestPipelinePart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCSIMPLECONTEXTREQUESTPIPELINEPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcSimpleContextRequestPipelinePart)

  })

_sym_db.RegisterMessage(GrpcSimpleContextRequestPipelinePart)



GrpcComplexRequestPart = _reflection.GeneratedProtocolMessageType('GrpcComplexRequestPart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCCOMPLEXREQUESTPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcComplexRequestPart)

  })

_sym_db.RegisterMessage(GrpcComplexRequestPart)



if _descriptor._USE_C_DESCRIPTORS == False:



  DESCRIPTOR._options = None

  _GRPCPIPELINE._serialized_start=41

  _GRPCPIPELINE._serialized_end=99

  _GRPCPIPELINEPARTBASE._serialized_start=102

  _GRPCPIPELINEPARTBASE._serialized_end=386

  _GRPCPIPELINEPART._serialized_start=388

  _GRPCPIPELINEPART._serialized_end=481

  _GRPCPIPELINEPARTCONFIGURATION._serialized_start=483

  _GRPCPIPELINEPARTCONFIGURATION._serialized_end=575

  _GRPCPARALLELPIPELINEPART._serialized_start=577

  _GRPCPARALLELPIPELINEPART._serialized_end=655

  _GRPCPARALLELPIPELINEPARTS._serialized_start=657

  _GRPCPARALLELPIPELINEPARTS._serialized_end=735

  _GRPCSIMPLECONTEXTREQUESTPIPELINEPART._serialized_start=737

  _GRPCSIMPLECONTEXTREQUESTPIPELINEPART._serialized_end=811

  _GRPCCOMPLEXREQUESTPART._serialized_start=813

  _GRPCCOMPLEXREQUESTPART._serialized_end=926

# @@protoc_insertion_point(module_scope)
