# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: pipelines.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()





import ficus.grpc_pipelines.models.context_pb2 as context__pb2





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpipelines.proto\x12\x05\x66icus\x1a\rcontext.proto\":\n\x0cGrpcPipeline\x12*\n\x05parts\x18\x01 \x03(\x0b\x32\x1b.ficus.GrpcPipelinePartBase\"\x87\x01\n\x14GrpcPipelinePartBase\x12.\n\x0b\x64\x65\x66\x61ultPart\x18\x01 \x01(\x0b\x32\x17.ficus.GrpcPipelinePartH\x00\x12\x37\n\x0cparallelPart\x18\x02 \x01(\x0b\x32\x1f.ficus.GrpcParallelPipelinePartH\x00\x42\x06\n\x04part\"]\n\x10GrpcPipelinePart\x12\x0c\n\x04name\x18\x01 \x01(\t\x12;\n\rconfiguration\x18\x02 \x01(\x0b\x32$.ficus.GrpcPipelinePartConfiguration\"\\\n\x1dGrpcPipelinePartConfiguration\x12;\n\x17\x63onfigurationParameters\x18\x01 \x03(\x0b\x32\x1a.ficus.GrpcContextKeyValue\"N\n\x18GrpcParallelPipelinePart\x12\x32\n\rpipelineParts\x18\x01 \x03(\x0b\x32\x1b.ficus.GrpcPipelinePartBase\"N\n\x19GrpcParallelPipelineParts\x12\x31\n\x08pipeline\x18\x01 \x03(\x0b\x32\x1f.ficus.GrpcParallelPipelinePartb\x06proto3')







_GRPCPIPELINE = DESCRIPTOR.message_types_by_name['GrpcPipeline']

_GRPCPIPELINEPARTBASE = DESCRIPTOR.message_types_by_name['GrpcPipelinePartBase']

_GRPCPIPELINEPART = DESCRIPTOR.message_types_by_name['GrpcPipelinePart']

_GRPCPIPELINEPARTCONFIGURATION = DESCRIPTOR.message_types_by_name['GrpcPipelinePartConfiguration']

_GRPCPARALLELPIPELINEPART = DESCRIPTOR.message_types_by_name['GrpcParallelPipelinePart']

_GRPCPARALLELPIPELINEPARTS = DESCRIPTOR.message_types_by_name['GrpcParallelPipelineParts']

GrpcPipeline = _reflection.GeneratedProtocolMessageType('GrpcPipeline', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINE,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipeline)

  })

_sym_db.RegisterMessage(GrpcPipeline)



GrpcPipelinePartBase = _reflection.GeneratedProtocolMessageType('GrpcPipelinePartBase', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPARTBASE,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePartBase)

  })

_sym_db.RegisterMessage(GrpcPipelinePartBase)



GrpcPipelinePart = _reflection.GeneratedProtocolMessageType('GrpcPipelinePart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePart)

  })

_sym_db.RegisterMessage(GrpcPipelinePart)



GrpcPipelinePartConfiguration = _reflection.GeneratedProtocolMessageType('GrpcPipelinePartConfiguration', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPIPELINEPARTCONFIGURATION,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcPipelinePartConfiguration)

  })

_sym_db.RegisterMessage(GrpcPipelinePartConfiguration)



GrpcParallelPipelinePart = _reflection.GeneratedProtocolMessageType('GrpcParallelPipelinePart', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPARALLELPIPELINEPART,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcParallelPipelinePart)

  })

_sym_db.RegisterMessage(GrpcParallelPipelinePart)



GrpcParallelPipelineParts = _reflection.GeneratedProtocolMessageType('GrpcParallelPipelineParts', (_message.Message,), {

  'DESCRIPTOR' : _GRPCPARALLELPIPELINEPARTS,

  '__module__' : 'pipelines_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcParallelPipelineParts)

  })

_sym_db.RegisterMessage(GrpcParallelPipelineParts)



if _descriptor._USE_C_DESCRIPTORS == False:



  DESCRIPTOR._options = None

  _GRPCPIPELINE._serialized_start=41

  _GRPCPIPELINE._serialized_end=99

  _GRPCPIPELINEPARTBASE._serialized_start=102

  _GRPCPIPELINEPARTBASE._serialized_end=237

  _GRPCPIPELINEPART._serialized_start=239

  _GRPCPIPELINEPART._serialized_end=332

  _GRPCPIPELINEPARTCONFIGURATION._serialized_start=334

  _GRPCPIPELINEPARTCONFIGURATION._serialized_end=426

  _GRPCPARALLELPIPELINEPART._serialized_start=428

  _GRPCPARALLELPIPELINEPART._serialized_end=506

  _GRPCPARALLELPIPELINEPARTS._serialized_start=508

  _GRPCPARALLELPIPELINEPARTS._serialized_end=586

# @@protoc_insertion_point(module_scope)
