# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: util.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import message as _message

from google.protobuf import reflection as _reflection

from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()









DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nutil.proto\x12\x05\x66icus\"\x18\n\x08GrpcGuid\x12\x0c\n\x04guid\x18\x01 \x01(\t\"5\n\tGrpcColor\x12\x0b\n\x03red\x18\x01 \x01(\r\x12\r\n\x05green\x18\x02 \x01(\r\x12\x0c\n\x04\x62lue\x18\x03 \x01(\r\"\x18\n\x08GrpcUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\tb\x06proto3')







_GRPCGUID = DESCRIPTOR.message_types_by_name['GrpcGuid']

_GRPCCOLOR = DESCRIPTOR.message_types_by_name['GrpcColor']

_GRPCUUID = DESCRIPTOR.message_types_by_name['GrpcUuid']

GrpcGuid = _reflection.GeneratedProtocolMessageType('GrpcGuid', (_message.Message,), {

  'DESCRIPTOR' : _GRPCGUID,

  '__module__' : 'util_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcGuid)

  })

_sym_db.RegisterMessage(GrpcGuid)



GrpcColor = _reflection.GeneratedProtocolMessageType('GrpcColor', (_message.Message,), {

  'DESCRIPTOR' : _GRPCCOLOR,

  '__module__' : 'util_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcColor)

  })

_sym_db.RegisterMessage(GrpcColor)



GrpcUuid = _reflection.GeneratedProtocolMessageType('GrpcUuid', (_message.Message,), {

  'DESCRIPTOR' : _GRPCUUID,

  '__module__' : 'util_pb2'

  # @@protoc_insertion_point(class_scope:ficus.GrpcUuid)

  })

_sym_db.RegisterMessage(GrpcUuid)



if _descriptor._USE_C_DESCRIPTORS == False:



  DESCRIPTOR._options = None

  _GRPCGUID._serialized_start=21

  _GRPCGUID._serialized_end=45

  _GRPCCOLOR._serialized_start=47

  _GRPCCOLOR._serialized_end=100

  _GRPCUUID._serialized_start=102

  _GRPCUUID._serialized_end=126

# @@protoc_insertion_point(module_scope)
