const_read_log_from_xes = 'ReadLogFromXes'
const_colors_event_log = 'colors_event_log'
const_event_name = 'event_name'
const_regex = 'regex'
const_tandem_array_length = 'tandem_array_length'
const_patterns_discovery_strategy = 'patterns_discovery_strategy'
const_activity_level = 'activity_level'
const_narrow_activities = 'narrow_activities'

const_draw_placement_of_event_by_regex = 'DrawPlacementOfEventsByRegex'
const_draw_full_activities_diagram = 'DrawFullActivitiesDiagram'
const_draw_short_activities_diagram = 'DrawShortActivitiesDiagram'
const_draw_placement_of_event_by_name = 'DrawPlacementOfEventByName'
const_find_primitive_tandem_arrays = 'FindPrimitiveTandemArrays'
const_find_maximal_tandem_arrays = 'FindMaximalTandemArrays'
const_find_maximal_repeats = 'FindMaximalRepeats'
const_find_super_maximal_repeats = 'FindSuperMaximalRepeats'
const_find_near_super_maximal_repeats = 'FindNearSuperMaximalRepeats'
const_discover_activities = 'DiscoverActivities'
const_discover_activities_instances = 'DiscoverActivitiesInstances'

const_pattern_discovery_strategy_enum_name = 'PatternsDiscoveryStrategy'
